import random
import pandas as pd

negative_pictures = ["A011.jpg", "A038.jpg", "A040.jpg", "A042.jpg", "A062.jpg", "A115.jpg", "A123.jpg", "A127.jpg", "I169.jpg", "OASIS_I166.jpg", "OASIS_I167.jpg", "OASIS_I22.jpg", "OASIS_I24.jpg", "OASIS_I273.jpg", "OASIS_I274.jpg", "OASIS_I281.jpg", "OASIS_I282.jpg", "Sn079.jpg", "Sp009.jpg", "Sp020.jpg", "Sp051.jpg", "Sp075.jpg", "Sp125.jpg", "Sp126.jpg"]
neutral_pictures = ["N003.bmp", "N004.bmp", "N006.bmp", "N009.bmp", "N010.bmp", "N011.bmp", "N014.bmp", "N017.bmp", "N020.bmp", "N024.bmp", "N026.bmp", "N028.bmp", "N031.bmp", "N036.bmp", "N040.bmp", "N047.bmp", "N061.bmp", "N067.bmp", "N070.bmp", "N081.bmp", "N082.bmp", "N091.bmp", "N092.bmp", "N102.bmp"]
positive_pictures = ["I132.jpg", "OASIS_I133.jpg", "OASIS_I134.jpg", "OASIS_I252.jpg", "OASIS_I254.jpg", "OASIS_I256.jpg", "P060.jpg", "P066.jpg", "P073.jpg", "P075.jpg", "P077.jpg", "P078.jpg", "P079.jpg", "P080.jpg", "P081.jpg", "P082.jpg", "P083.jpg", "P095.jpg", "P096.jpg", "P099.jpg", "P101.jpg", "P113.jpg", "P114.jpg", "P122.jpg"]
video_filenames = ["BabyCooking.mp4", "BabyTeeth.mp4", "BabyTree.mp4", "Backflips.mp4", "Ballerina.mp4", "Ballett.mp4", "Basketball.mp4", "Beard.mp4", "Bicycle.mp4", "BicycleBoy.mp4", "Boysplaying.mp4", "Canoe.mp4", "CarDriving.mp4", "ChildHockey.mp4", "CityWalking.mp4", "CookingDadDaughter.mp4", "CookingMan.mp4", "CookingPumpkin.mp4", "CookingShow.mp4", "CookingShowII.mp4", "DancingGirl.mp4", "DancingGuy.mp4", "DiscusThrow.mp4", "DogWalking.mp4", "DrivingCar.mp4", "GiftWrapping.mp4", "GrandmaJumping.mp4", "GrassTrimming.mp4", "GrassTrimmingII.mp4", "GuySmoking.mp4", "GymnasticsChina.mp4", "HairMannequin.mp4", "HairStyling.mp4", "HairdresserDonation.mp4", "Hairrollers.mp4", "Harmonica.mp4", "HarmonicaStanding.mp4", "HighJump.mp4", "HorseRiding.mp4", "HorseTrail.mp4", "Interview.mp4", "KidswithDad.mp4", "MakeupArtist.mp4", "MakeupArtistGirl.mp4", "ManBikeRiding.mp4", "Motorbikes.mp4", "Nails.mp4", "PianoRecital.mp4", "PianoYanni.mp4", "Pipes.mp4", "PoolJumping.mp4", "PoolJumpingOutdoors.mp4", "RockClimbing.mp4", "RockClimbingII.mp4", "ShoeCleaning.mp4", "ShoeCleaningII.mp4", "SnowShovelling.mp4", "Spinning.mp4", "Tennis.mp4", "Vaccum.mp4", "WalkingDog.mp4", "WashingBedsheets.mp4", "WashingDishes.mp4", "WashingFace.mp4", "Weightlifing.mp4", "WhaleWatching.mp4", "WindowCleaner.mp4", "WindowCleanersCostumes.mp4", "WomanCooking.mp4", "WoodchoppingDog.mp4", "WoodchoppingSnow.mp4", "Woodpolishing.mp4"]

random.shuffle(negative_pictures)
random.shuffle(neutral_pictures)
random.shuffle(positive_pictures)
random.shuffle(video_filenames)

video_set_a = video_filenames[0:24]
video_set_b = video_filenames[24:48]
video_set_c = video_filenames[48:72]

trial_list_mapping_1 = [
    {"vid": video_set_a[0], "img": negative_pictures[0], "valence": "negative", "n": 1 , "list": 1},
    {"vid": video_set_a[1], "img": negative_pictures[1], "valence": "negative", "n": 2 , "list": 1},
    {"vid": video_set_a[2], "img": negative_pictures[2], "valence": "negative", "n": 3 , "list": 1},
    {"vid": video_set_a[3], "img": negative_pictures[3], "valence": "negative", "n": 4 , "list": 1},
    {"vid": video_set_a[4], "img": negative_pictures[4], "valence": "negative", "n": 5 , "list": 1},
    {"vid": video_set_a[5], "img": negative_pictures[5], "valence": "negative", "n": 6 , "list": 1},
    {"vid": video_set_a[6], "img": negative_pictures[6], "valence": "negative", "n": 7 , "list": 1},
    {"vid": video_set_a[7], "img": negative_pictures[7], "valence": "negative", "n": 8 , "list": 1},
    {"vid": video_set_a[8], "img": negative_pictures[8], "valence": "negative", "n": 9 , "list": 1},
    {"vid": video_set_a[9], "img": negative_pictures[9], "valence": "negative", "n": 10 , "list": 1},
    {"vid": video_set_a[10], "img": negative_pictures[10], "valence": "negative", "n": 11 , "list": 1},
    {"vid": video_set_a[11], "img": negative_pictures[11], "valence": "negative", "n": 12 , "list": 1},
    {"vid": video_set_a[12], "img": negative_pictures[12], "valence": "negative", "n": 13 , "list": 1},
    {"vid": video_set_a[13], "img": negative_pictures[13], "valence": "negative", "n": 14 , "list": 1},
    {"vid": video_set_a[14], "img": negative_pictures[14], "valence": "negative", "n": 15 , "list": 1},
    {"vid": video_set_a[15], "img": negative_pictures[15], "valence": "negative", "n": 16 , "list": 1},
    {"vid": video_set_a[16], "img": negative_pictures[16], "valence": "negative", "n": 17 , "list": 1},
    {"vid": video_set_a[17], "img": negative_pictures[17], "valence": "negative", "n": 18 , "list": 1},
    {"vid": video_set_a[18], "img": negative_pictures[18], "valence": "negative", "n": 19 , "list": 1},
    {"vid": video_set_a[19], "img": negative_pictures[19], "valence": "negative", "n": 20 , "list": 1},
    {"vid": video_set_a[20], "img": negative_pictures[20], "valence": "negative", "n": 21 , "list": 1},
    {"vid": video_set_a[21], "img": negative_pictures[21], "valence": "negative", "n": 22 , "list": 1},
    {"vid": video_set_a[22], "img": negative_pictures[22], "valence": "negative", "n": 23 , "list": 1},
    {"vid": video_set_a[23], "img": negative_pictures[23], "valence": "negative", "n": 24 , "list": 1},
    {"vid": video_set_b[0], "img": neutral_pictures[0], "valence": "neutral", "n": 25 , "list": 1},
    {"vid": video_set_b[1], "img": neutral_pictures[1], "valence": "neutral", "n": 26 , "list": 1},
    {"vid": video_set_b[2], "img": neutral_pictures[2], "valence": "neutral", "n": 27 , "list": 1},
    {"vid": video_set_b[3], "img": neutral_pictures[3], "valence": "neutral", "n": 28 , "list": 1},
    {"vid": video_set_b[4], "img": neutral_pictures[4], "valence": "neutral", "n": 29 , "list": 1},
    {"vid": video_set_b[5], "img": neutral_pictures[5], "valence": "neutral", "n": 30 , "list": 1},
    {"vid": video_set_b[6], "img": neutral_pictures[6], "valence": "neutral", "n": 31 , "list": 1},
    {"vid": video_set_b[7], "img": neutral_pictures[7], "valence": "neutral", "n": 32 , "list": 1},
    {"vid": video_set_b[8], "img": neutral_pictures[8], "valence": "neutral", "n": 33 , "list": 1},
    {"vid": video_set_b[9], "img": neutral_pictures[9], "valence": "neutral", "n": 34 , "list": 1},
    {"vid": video_set_b[10], "img": neutral_pictures[10], "valence": "neutral", "n": 35 , "list": 1},
    {"vid": video_set_b[11], "img": neutral_pictures[11], "valence": "neutral", "n": 36 , "list": 1},
    {"vid": video_set_b[12], "img": neutral_pictures[12], "valence": "neutral", "n": 37 , "list": 1},
    {"vid": video_set_b[13], "img": neutral_pictures[13], "valence": "neutral", "n": 38 , "list": 1},
    {"vid": video_set_b[14], "img": neutral_pictures[14], "valence": "neutral", "n": 39 , "list": 1},
    {"vid": video_set_b[15], "img": neutral_pictures[15], "valence": "neutral", "n": 40 , "list": 1},
    {"vid": video_set_b[16], "img": neutral_pictures[16], "valence": "neutral", "n": 41 , "list": 1},
    {"vid": video_set_b[17], "img": neutral_pictures[17], "valence": "neutral", "n": 42 , "list": 1},
    {"vid": video_set_b[18], "img": neutral_pictures[18], "valence": "neutral", "n": 43 , "list": 1},
    {"vid": video_set_b[19], "img": neutral_pictures[19], "valence": "neutral", "n": 44 , "list": 1},
    {"vid": video_set_b[20], "img": neutral_pictures[20], "valence": "neutral", "n": 45 , "list": 1},
    {"vid": video_set_b[21], "img": neutral_pictures[21], "valence": "neutral", "n": 46 , "list": 1},
    {"vid": video_set_b[22], "img": neutral_pictures[22], "valence": "neutral", "n": 47 , "list": 1},
    {"vid": video_set_b[23], "img": neutral_pictures[23], "valence": "neutral", "n": 48 , "list": 1},
    {"vid": video_set_c[0], "img": positive_pictures[0], "valence": "positive", "n": 49 , "list": 1},
    {"vid": video_set_c[1], "img": positive_pictures[1], "valence": "positive", "n": 50 , "list": 1},
    {"vid": video_set_c[2], "img": positive_pictures[2], "valence": "positive", "n": 51 , "list": 1},
    {"vid": video_set_c[3], "img": positive_pictures[3], "valence": "positive", "n": 52 , "list": 1},
    {"vid": video_set_c[4], "img": positive_pictures[4], "valence": "positive", "n": 53 , "list": 1},
    {"vid": video_set_c[5], "img": positive_pictures[5], "valence": "positive", "n": 54 , "list": 1},
    {"vid": video_set_c[6], "img": positive_pictures[6], "valence": "positive", "n": 55 , "list": 1},
    {"vid": video_set_c[7], "img": positive_pictures[7], "valence": "positive", "n": 56 , "list": 1},
    {"vid": video_set_c[8], "img": positive_pictures[8], "valence": "positive", "n": 57 , "list": 1},
    {"vid": video_set_c[9], "img": positive_pictures[9], "valence": "positive", "n": 58 , "list": 1},
    {"vid": video_set_c[10], "img": positive_pictures[10], "valence": "positive", "n": 59 , "list": 1},
    {"vid": video_set_c[11], "img": positive_pictures[11], "valence": "positive", "n": 60 , "list": 1},
    {"vid": video_set_c[12], "img": positive_pictures[12], "valence": "positive", "n": 61 , "list": 1},
    {"vid": video_set_c[13], "img": positive_pictures[13], "valence": "positive", "n": 62 , "list": 1},
    {"vid": video_set_c[14], "img": positive_pictures[14], "valence": "positive", "n": 63 , "list": 1},
    {"vid": video_set_c[15], "img": positive_pictures[15], "valence": "positive", "n": 64 , "list": 1},
    {"vid": video_set_c[16], "img": positive_pictures[16], "valence": "positive", "n": 65 , "list": 1},
    {"vid": video_set_c[17], "img": positive_pictures[17], "valence": "positive", "n": 66 , "list": 1},
    {"vid": video_set_c[18], "img": positive_pictures[18], "valence": "positive", "n": 67 , "list": 1},
    {"vid": video_set_c[19], "img": positive_pictures[19], "valence": "positive", "n": 68 , "list": 1},
    {"vid": video_set_c[20], "img": positive_pictures[20], "valence": "positive", "n": 69 , "list": 1},
    {"vid": video_set_c[21], "img": positive_pictures[21], "valence": "positive", "n": 70 , "list": 1},
    {"vid": video_set_c[22], "img": positive_pictures[22], "valence": "positive", "n": 71 , "list": 1},
    {"vid": video_set_c[23], "img": positive_pictures[23], "valence": "positive", "n": 72 , "list": 1}
]

# Each block has 8 positive, 8 negative, 8 neutral trials

trial_list_mapping_1_block_1 = [
    {"vid": video_set_a[0], "img": negative_pictures[0], "valence": "negative", "n": 1 , "list": 1},
    {"vid": video_set_a[1], "img": negative_pictures[1], "valence": "negative", "n": 2 , "list": 1},
    {"vid": video_set_a[2], "img": negative_pictures[2], "valence": "negative", "n": 3 , "list": 1},
    {"vid": video_set_a[3], "img": negative_pictures[3], "valence": "negative", "n": 4 , "list": 1},
    {"vid": video_set_a[4], "img": negative_pictures[4], "valence": "negative", "n": 5 , "list": 1},
    {"vid": video_set_a[5], "img": negative_pictures[5], "valence": "negative", "n": 6 , "list": 1},
    {"vid": video_set_a[6], "img": negative_pictures[6], "valence": "negative", "n": 7 , "list": 1},
    {"vid": video_set_a[7], "img": negative_pictures[7], "valence": "negative", "n": 8 , "list": 1},

    {"vid": video_set_b[0], "img": neutral_pictures[0], "valence": "neutral", "n": 25 , "list": 1},
    {"vid": video_set_b[1], "img": neutral_pictures[1], "valence": "neutral", "n": 26 , "list": 1},
    {"vid": video_set_b[2], "img": neutral_pictures[2], "valence": "neutral", "n": 27 , "list": 1},
    {"vid": video_set_b[3], "img": neutral_pictures[3], "valence": "neutral", "n": 28 , "list": 1},
    {"vid": video_set_b[4], "img": neutral_pictures[4], "valence": "neutral", "n": 29 , "list": 1},
    {"vid": video_set_b[5], "img": neutral_pictures[5], "valence": "neutral", "n": 30 , "list": 1},
    {"vid": video_set_b[6], "img": neutral_pictures[6], "valence": "neutral", "n": 31 , "list": 1},
    {"vid": video_set_b[7], "img": neutral_pictures[7], "valence": "neutral", "n": 32 , "list": 1},
    
    {"vid": video_set_c[0], "img": positive_pictures[0], "valence": "positive", "n": 49 , "list": 1},
    {"vid": video_set_c[1], "img": positive_pictures[1], "valence": "positive", "n": 50 , "list": 1},
    {"vid": video_set_c[2], "img": positive_pictures[2], "valence": "positive", "n": 51 , "list": 1},
    {"vid": video_set_c[3], "img": positive_pictures[3], "valence": "positive", "n": 52 , "list": 1},
    {"vid": video_set_c[4], "img": positive_pictures[4], "valence": "positive", "n": 53 , "list": 1},
    {"vid": video_set_c[5], "img": positive_pictures[5], "valence": "positive", "n": 54 , "list": 1},
    {"vid": video_set_c[6], "img": positive_pictures[6], "valence": "positive", "n": 55 , "list": 1},
    {"vid": video_set_c[7], "img": positive_pictures[7], "valence": "positive", "n": 56 , "list": 1},
]

trial_list_mapping_1_block_2 = [
    {"vid": video_set_a[8], "img": negative_pictures[8], "valence": "negative", "n": 9 , "list": 1},
    {"vid": video_set_a[9], "img": negative_pictures[9], "valence": "negative", "n": 10 , "list": 1},
    {"vid": video_set_a[10], "img": negative_pictures[10], "valence": "negative", "n": 11 , "list": 1},
    {"vid": video_set_a[11], "img": negative_pictures[11], "valence": "negative", "n": 12 , "list": 1},
    {"vid": video_set_a[12], "img": negative_pictures[12], "valence": "negative", "n": 13 , "list": 1},
    {"vid": video_set_a[13], "img": negative_pictures[13], "valence": "negative", "n": 14 , "list": 1},
    {"vid": video_set_a[14], "img": negative_pictures[14], "valence": "negative", "n": 15 , "list": 1},
    {"vid": video_set_a[15], "img": negative_pictures[15], "valence": "negative", "n": 16 , "list": 1},

    {"vid": video_set_b[8], "img": neutral_pictures[8], "valence": "neutral", "n": 33 , "list": 1},
    {"vid": video_set_b[9], "img": neutral_pictures[9], "valence": "neutral", "n": 34 , "list": 1},
    {"vid": video_set_b[10], "img": neutral_pictures[10], "valence": "neutral", "n": 35 , "list": 1},
    {"vid": video_set_b[11], "img": neutral_pictures[11], "valence": "neutral", "n": 36 , "list": 1},
    {"vid": video_set_b[12], "img": neutral_pictures[12], "valence": "neutral", "n": 37 , "list": 1},
    {"vid": video_set_b[13], "img": neutral_pictures[13], "valence": "neutral", "n": 38 , "list": 1},
    {"vid": video_set_b[14], "img": neutral_pictures[14], "valence": "neutral", "n": 39 , "list": 1},
    {"vid": video_set_b[15], "img": neutral_pictures[15], "valence": "neutral", "n": 40 , "list": 1},
    
    {"vid": video_set_c[8], "img": positive_pictures[8], "valence": "positive", "n": 57 , "list": 1},
    {"vid": video_set_c[9], "img": positive_pictures[9], "valence": "positive", "n": 58 , "list": 1},
    {"vid": video_set_c[10], "img": positive_pictures[10], "valence": "positive", "n": 59 , "list": 1},
    {"vid": video_set_c[11], "img": positive_pictures[11], "valence": "positive", "n": 60 , "list": 1},
    {"vid": video_set_c[12], "img": positive_pictures[12], "valence": "positive", "n": 61 , "list": 1},
    {"vid": video_set_c[13], "img": positive_pictures[13], "valence": "positive", "n": 62 , "list": 1},
    {"vid": video_set_c[14], "img": positive_pictures[14], "valence": "positive", "n": 63 , "list": 1},
    {"vid": video_set_c[15], "img": positive_pictures[15], "valence": "positive", "n": 64 , "list": 1},
    
]

trial_list_mapping_1_block_3 = [
    {"vid": video_set_a[16], "img": negative_pictures[16], "valence": "negative", "n": 17 , "list": 1},
    {"vid": video_set_a[17], "img": negative_pictures[17], "valence": "negative", "n": 18 , "list": 1},
    {"vid": video_set_a[18], "img": negative_pictures[18], "valence": "negative", "n": 19 , "list": 1},
    {"vid": video_set_a[19], "img": negative_pictures[19], "valence": "negative", "n": 20 , "list": 1},
    {"vid": video_set_a[20], "img": negative_pictures[20], "valence": "negative", "n": 21 , "list": 1},
    {"vid": video_set_a[21], "img": negative_pictures[21], "valence": "negative", "n": 22 , "list": 1},
    {"vid": video_set_a[22], "img": negative_pictures[22], "valence": "negative", "n": 23 , "list": 1},
    {"vid": video_set_a[23], "img": negative_pictures[23], "valence": "negative", "n": 24 , "list": 1},
    
    {"vid": video_set_b[16], "img": neutral_pictures[16], "valence": "neutral", "n": 41 , "list": 1},
    {"vid": video_set_b[17], "img": neutral_pictures[17], "valence": "neutral", "n": 42 , "list": 1},
    {"vid": video_set_b[18], "img": neutral_pictures[18], "valence": "neutral", "n": 43 , "list": 1},
    {"vid": video_set_b[19], "img": neutral_pictures[19], "valence": "neutral", "n": 44 , "list": 1},
    {"vid": video_set_b[20], "img": neutral_pictures[20], "valence": "neutral", "n": 45 , "list": 1},
    {"vid": video_set_b[21], "img": neutral_pictures[21], "valence": "neutral", "n": 46 , "list": 1},
    {"vid": video_set_b[22], "img": neutral_pictures[22], "valence": "neutral", "n": 47 , "list": 1},
    {"vid": video_set_b[23], "img": neutral_pictures[23], "valence": "neutral", "n": 48 , "list": 1},
    
    {"vid": video_set_c[16], "img": positive_pictures[16], "valence": "positive", "n": 65 , "list": 1},
    {"vid": video_set_c[17], "img": positive_pictures[17], "valence": "positive", "n": 66 , "list": 1},
    {"vid": video_set_c[18], "img": positive_pictures[18], "valence": "positive", "n": 67 , "list": 1},
    {"vid": video_set_c[19], "img": positive_pictures[19], "valence": "positive", "n": 68 , "list": 1},
    {"vid": video_set_c[20], "img": positive_pictures[20], "valence": "positive", "n": 69 , "list": 1},
    {"vid": video_set_c[21], "img": positive_pictures[21], "valence": "positive", "n": 70 , "list": 1},
    {"vid": video_set_c[22], "img": positive_pictures[22], "valence": "positive", "n": 71 , "list": 1},
    {"vid": video_set_c[23], "img": positive_pictures[23], "valence": "positive", "n": 72 , "list": 1}
]

trial_list_mapping_2 = [
    {"vid": video_set_a[0], "img": neutral_pictures[0], "valence": "neutral", "n": 1 , "list": 2},
    {"vid": video_set_a[1], "img": neutral_pictures[1], "valence": "neutral", "n": 2 , "list": 2},
    {"vid": video_set_a[2], "img": neutral_pictures[2], "valence": "neutral", "n": 3 , "list": 2},
    {"vid": video_set_a[3], "img": neutral_pictures[3], "valence": "neutral", "n": 4 , "list": 2},
    {"vid": video_set_a[4], "img": neutral_pictures[4], "valence": "neutral", "n": 5 , "list": 2},
    {"vid": video_set_a[5], "img": neutral_pictures[5], "valence": "neutral", "n": 6 , "list": 2},
    {"vid": video_set_a[6], "img": neutral_pictures[6], "valence": "neutral", "n": 7 , "list": 2},
    {"vid": video_set_a[7], "img": neutral_pictures[7], "valence": "neutral", "n": 8 , "list": 2},
    {"vid": video_set_a[8], "img": neutral_pictures[8], "valence": "neutral", "n": 9 , "list": 2},
    {"vid": video_set_a[9], "img": neutral_pictures[9], "valence": "neutral", "n": 10 , "list": 2},
    {"vid": video_set_a[10], "img": neutral_pictures[10], "valence": "neutral", "n": 11 , "list": 2},
    {"vid": video_set_a[11], "img": neutral_pictures[11], "valence": "neutral", "n": 12 , "list": 2},
    {"vid": video_set_a[12], "img": neutral_pictures[12], "valence": "neutral", "n": 13 , "list": 2},
    {"vid": video_set_a[13], "img": neutral_pictures[13], "valence": "neutral", "n": 14 , "list": 2},
    {"vid": video_set_a[14], "img": neutral_pictures[14], "valence": "neutral", "n": 15 , "list": 2},
    {"vid": video_set_a[15], "img": neutral_pictures[15], "valence": "neutral", "n": 16 , "list": 2},
    {"vid": video_set_a[16], "img": neutral_pictures[16], "valence": "neutral", "n": 17 , "list": 2},
    {"vid": video_set_a[17], "img": neutral_pictures[17], "valence": "neutral", "n": 18 , "list": 2},
    {"vid": video_set_a[18], "img": neutral_pictures[18], "valence": "neutral", "n": 19 , "list": 2},
    {"vid": video_set_a[19], "img": neutral_pictures[19], "valence": "neutral", "n": 20 , "list": 2},
    {"vid": video_set_a[20], "img": neutral_pictures[20], "valence": "neutral", "n": 21 , "list": 2},
    {"vid": video_set_a[21], "img": neutral_pictures[21], "valence": "neutral", "n": 22 , "list": 2},
    {"vid": video_set_a[22], "img": neutral_pictures[22], "valence": "neutral", "n": 23 , "list": 2},
    {"vid": video_set_a[23], "img": neutral_pictures[23], "valence": "neutral", "n": 24 , "list": 2},
    {"vid": video_set_b[0], "img": positive_pictures[0], "valence": "positive", "n": 25 , "list": 2},
    {"vid": video_set_b[1], "img": positive_pictures[1], "valence": "positive", "n": 26 , "list": 2},
    {"vid": video_set_b[2], "img": positive_pictures[2], "valence": "positive", "n": 27 , "list": 2},
    {"vid": video_set_b[3], "img": positive_pictures[3], "valence": "positive", "n": 28 , "list": 2},
    {"vid": video_set_b[4], "img": positive_pictures[4], "valence": "positive", "n": 29 , "list": 2},
    {"vid": video_set_b[5], "img": positive_pictures[5], "valence": "positive", "n": 30 , "list": 2},
    {"vid": video_set_b[6], "img": positive_pictures[6], "valence": "positive", "n": 31 , "list": 2},
    {"vid": video_set_b[7], "img": positive_pictures[7], "valence": "positive", "n": 32 , "list": 2},
    {"vid": video_set_b[8], "img": positive_pictures[8], "valence": "positive", "n": 33 , "list": 2},
    {"vid": video_set_b[9], "img": positive_pictures[9], "valence": "positive", "n": 34 , "list": 2},
    {"vid": video_set_b[10], "img": positive_pictures[10], "valence": "positive", "n": 35 , "list": 2},
    {"vid": video_set_b[11], "img": positive_pictures[11], "valence": "positive", "n": 36 , "list": 2},
    {"vid": video_set_b[12], "img": positive_pictures[12], "valence": "positive", "n": 37 , "list": 2},
    {"vid": video_set_b[13], "img": positive_pictures[13], "valence": "positive", "n": 38 , "list": 2},
    {"vid": video_set_b[14], "img": positive_pictures[14], "valence": "positive", "n": 39 , "list": 2},
    {"vid": video_set_b[15], "img": positive_pictures[15], "valence": "positive", "n": 40 , "list": 2},
    {"vid": video_set_b[16], "img": positive_pictures[16], "valence": "positive", "n": 41 , "list": 2},
    {"vid": video_set_b[17], "img": positive_pictures[17], "valence": "positive", "n": 42 , "list": 2},
    {"vid": video_set_b[18], "img": positive_pictures[18], "valence": "positive", "n": 43 , "list": 2},
    {"vid": video_set_b[19], "img": positive_pictures[19], "valence": "positive", "n": 44 , "list": 2},
    {"vid": video_set_b[20], "img": positive_pictures[20], "valence": "positive", "n": 45 , "list": 2},
    {"vid": video_set_b[21], "img": positive_pictures[21], "valence": "positive", "n": 46 , "list": 2},
    {"vid": video_set_b[22], "img": positive_pictures[22], "valence": "positive", "n": 47 , "list": 2},
    {"vid": video_set_b[23], "img": positive_pictures[23], "valence": "positive", "n": 48 , "list": 2},
    {"vid": video_set_c[0], "img": negative_pictures[0], "valence": "negative", "n": 49 , "list": 2},
    {"vid": video_set_c[1], "img": negative_pictures[1], "valence": "negative", "n": 50 , "list": 2},
    {"vid": video_set_c[2], "img": negative_pictures[2], "valence": "negative", "n": 51 , "list": 2},
    {"vid": video_set_c[3], "img": negative_pictures[3], "valence": "negative", "n": 52 , "list": 2},
    {"vid": video_set_c[4], "img": negative_pictures[4], "valence": "negative", "n": 53 , "list": 2},
    {"vid": video_set_c[5], "img": negative_pictures[5], "valence": "negative", "n": 54 , "list": 2},
    {"vid": video_set_c[6], "img": negative_pictures[6], "valence": "negative", "n": 55 , "list": 2},
    {"vid": video_set_c[7], "img": negative_pictures[7], "valence": "negative", "n": 56 , "list": 2},
    {"vid": video_set_c[8], "img": negative_pictures[8], "valence": "negative", "n": 57 , "list": 2},
    {"vid": video_set_c[9], "img": negative_pictures[9], "valence": "negative", "n": 58 , "list": 2},
    {"vid": video_set_c[10], "img": negative_pictures[10], "valence": "negative", "n": 59 , "list": 2},
    {"vid": video_set_c[11], "img": negative_pictures[11], "valence": "negative", "n": 60 , "list": 2},
    {"vid": video_set_c[12], "img": negative_pictures[12], "valence": "negative", "n": 61 , "list": 2},
    {"vid": video_set_c[13], "img": negative_pictures[13], "valence": "negative", "n": 62 , "list": 2},
    {"vid": video_set_c[14], "img": negative_pictures[14], "valence": "negative", "n": 63 , "list": 2},
    {"vid": video_set_c[15], "img": negative_pictures[15], "valence": "negative", "n": 64 , "list": 2},
    {"vid": video_set_c[16], "img": negative_pictures[16], "valence": "negative", "n": 65 , "list": 2},
    {"vid": video_set_c[17], "img": negative_pictures[17], "valence": "negative", "n": 66 , "list": 2},
    {"vid": video_set_c[18], "img": negative_pictures[18], "valence": "negative", "n": 67 , "list": 2},
    {"vid": video_set_c[19], "img": negative_pictures[19], "valence": "negative", "n": 68 , "list": 2},
    {"vid": video_set_c[20], "img": negative_pictures[20], "valence": "negative", "n": 69 , "list": 2},
    {"vid": video_set_c[21], "img": negative_pictures[21], "valence": "negative", "n": 70 , "list": 2},
    {"vid": video_set_c[22], "img": negative_pictures[22], "valence": "negative", "n": 71 , "list": 2},
    {"vid": video_set_c[23], "img": negative_pictures[23], "valence": "negative", "n": 72 , "list": 2},
]

trial_list_mapping_2_block_1 = [
    {"vid": video_set_a[0], "img": neutral_pictures[0], "valence": "neutral", "n": 1 , "list": 2},
    {"vid": video_set_a[1], "img": neutral_pictures[1], "valence": "neutral", "n": 2 , "list": 2},
    {"vid": video_set_a[2], "img": neutral_pictures[2], "valence": "neutral", "n": 3 , "list": 2},
    {"vid": video_set_a[3], "img": neutral_pictures[3], "valence": "neutral", "n": 4 , "list": 2},
    {"vid": video_set_a[4], "img": neutral_pictures[4], "valence": "neutral", "n": 5 , "list": 2},
    {"vid": video_set_a[5], "img": neutral_pictures[5], "valence": "neutral", "n": 6 , "list": 2},
    {"vid": video_set_a[6], "img": neutral_pictures[6], "valence": "neutral", "n": 7 , "list": 2},
    {"vid": video_set_a[7], "img": neutral_pictures[7], "valence": "neutral", "n": 8 , "list": 2},

    {"vid": video_set_b[0], "img": positive_pictures[0], "valence": "positive", "n": 25 , "list": 2},
    {"vid": video_set_b[1], "img": positive_pictures[1], "valence": "positive", "n": 26 , "list": 2},
    {"vid": video_set_b[2], "img": positive_pictures[2], "valence": "positive", "n": 27 , "list": 2},
    {"vid": video_set_b[3], "img": positive_pictures[3], "valence": "positive", "n": 28 , "list": 2},
    {"vid": video_set_b[4], "img": positive_pictures[4], "valence": "positive", "n": 29 , "list": 2},
    {"vid": video_set_b[5], "img": positive_pictures[5], "valence": "positive", "n": 30 , "list": 2},
    {"vid": video_set_b[6], "img": positive_pictures[6], "valence": "positive", "n": 31 , "list": 2},
    {"vid": video_set_b[7], "img": positive_pictures[7], "valence": "positive", "n": 32 , "list": 2},

    {"vid": video_set_c[0], "img": negative_pictures[0], "valence": "negative", "n": 49 , "list": 2},
    {"vid": video_set_c[1], "img": negative_pictures[1], "valence": "negative", "n": 50 , "list": 2},
    {"vid": video_set_c[2], "img": negative_pictures[2], "valence": "negative", "n": 51 , "list": 2},
    {"vid": video_set_c[3], "img": negative_pictures[3], "valence": "negative", "n": 52 , "list": 2},
    {"vid": video_set_c[4], "img": negative_pictures[4], "valence": "negative", "n": 53 , "list": 2},
    {"vid": video_set_c[5], "img": negative_pictures[5], "valence": "negative", "n": 54 , "list": 2},
    {"vid": video_set_c[6], "img": negative_pictures[6], "valence": "negative", "n": 55 , "list": 2},
    {"vid": video_set_c[7], "img": negative_pictures[7], "valence": "negative", "n": 56 , "list": 2},
]

trial_list_mapping_2_block_2 = [
     {"vid": video_set_a[8], "img": neutral_pictures[8], "valence": "neutral", "n": 9 , "list": 2},
    {"vid": video_set_a[9], "img": neutral_pictures[9], "valence": "neutral", "n": 10 , "list": 2},
    {"vid": video_set_a[10], "img": neutral_pictures[10], "valence": "neutral", "n": 11 , "list": 2},
    {"vid": video_set_a[11], "img": neutral_pictures[11], "valence": "neutral", "n": 12 , "list": 2},
    {"vid": video_set_a[12], "img": neutral_pictures[12], "valence": "neutral", "n": 13 , "list": 2},
    {"vid": video_set_a[13], "img": neutral_pictures[13], "valence": "neutral", "n": 14 , "list": 2},
    {"vid": video_set_a[14], "img": neutral_pictures[14], "valence": "neutral", "n": 15 , "list": 2},
    {"vid": video_set_a[15], "img": neutral_pictures[15], "valence": "neutral", "n": 16 , "list": 2},

    {"vid": video_set_b[8], "img": positive_pictures[8], "valence": "positive", "n": 33 , "list": 2},
    {"vid": video_set_b[9], "img": positive_pictures[9], "valence": "positive", "n": 34 , "list": 2},
    {"vid": video_set_b[10], "img": positive_pictures[10], "valence": "positive", "n": 35 , "list": 2},
    {"vid": video_set_b[11], "img": positive_pictures[11], "valence": "positive", "n": 36 , "list": 2},
    {"vid": video_set_b[12], "img": positive_pictures[12], "valence": "positive", "n": 37 , "list": 2},
    {"vid": video_set_b[13], "img": positive_pictures[13], "valence": "positive", "n": 38 , "list": 2},
    {"vid": video_set_b[14], "img": positive_pictures[14], "valence": "positive", "n": 39 , "list": 2},
    {"vid": video_set_b[15], "img": positive_pictures[15], "valence": "positive", "n": 40 , "list": 2},

    {"vid": video_set_c[8], "img": negative_pictures[8], "valence": "negative", "n": 57 , "list": 2},
    {"vid": video_set_c[9], "img": negative_pictures[9], "valence": "negative", "n": 58 , "list": 2},
    {"vid": video_set_c[10], "img": negative_pictures[10], "valence": "negative", "n": 59 , "list": 2},
    {"vid": video_set_c[11], "img": negative_pictures[11], "valence": "negative", "n": 60 , "list": 2},
    {"vid": video_set_c[12], "img": negative_pictures[12], "valence": "negative", "n": 61 , "list": 2},
    {"vid": video_set_c[13], "img": negative_pictures[13], "valence": "negative", "n": 62 , "list": 2},
    {"vid": video_set_c[14], "img": negative_pictures[14], "valence": "negative", "n": 63 , "list": 2},
    {"vid": video_set_c[15], "img": negative_pictures[15], "valence": "negative", "n": 64 , "list": 2},
]

trial_list_mapping_2_block_3 = [
    {"vid": video_set_a[16], "img": neutral_pictures[16], "valence": "neutral", "n": 17 , "list": 2},
    {"vid": video_set_a[17], "img": neutral_pictures[17], "valence": "neutral", "n": 18 , "list": 2},
    {"vid": video_set_a[18], "img": neutral_pictures[18], "valence": "neutral", "n": 19 , "list": 2},
    {"vid": video_set_a[19], "img": neutral_pictures[19], "valence": "neutral", "n": 20 , "list": 2},
    {"vid": video_set_a[20], "img": neutral_pictures[20], "valence": "neutral", "n": 21 , "list": 2},
    {"vid": video_set_a[21], "img": neutral_pictures[21], "valence": "neutral", "n": 22 , "list": 2},
    {"vid": video_set_a[22], "img": neutral_pictures[22], "valence": "neutral", "n": 23 , "list": 2},
    {"vid": video_set_a[23], "img": neutral_pictures[23], "valence": "neutral", "n": 24 , "list": 2},

    {"vid": video_set_b[16], "img": positive_pictures[16], "valence": "positive", "n": 41 , "list": 2},
    {"vid": video_set_b[17], "img": positive_pictures[17], "valence": "positive", "n": 42 , "list": 2},
    {"vid": video_set_b[18], "img": positive_pictures[18], "valence": "positive", "n": 43 , "list": 2},
    {"vid": video_set_b[19], "img": positive_pictures[19], "valence": "positive", "n": 44 , "list": 2},
    {"vid": video_set_b[20], "img": positive_pictures[20], "valence": "positive", "n": 45 , "list": 2},
    {"vid": video_set_b[21], "img": positive_pictures[21], "valence": "positive", "n": 46 , "list": 2},
    {"vid": video_set_b[22], "img": positive_pictures[22], "valence": "positive", "n": 47 , "list": 2},
    {"vid": video_set_b[23], "img": positive_pictures[23], "valence": "positive", "n": 48 , "list": 2},

    {"vid": video_set_c[16], "img": negative_pictures[16], "valence": "negative", "n": 65 , "list": 2},
    {"vid": video_set_c[17], "img": negative_pictures[17], "valence": "negative", "n": 66 , "list": 2},
    {"vid": video_set_c[18], "img": negative_pictures[18], "valence": "negative", "n": 67 , "list": 2},
    {"vid": video_set_c[19], "img": negative_pictures[19], "valence": "negative", "n": 68 , "list": 2},
    {"vid": video_set_c[20], "img": negative_pictures[20], "valence": "negative", "n": 69 , "list": 2},
    {"vid": video_set_c[21], "img": negative_pictures[21], "valence": "negative", "n": 70 , "list": 2},
    {"vid": video_set_c[22], "img": negative_pictures[22], "valence": "negative", "n": 71 , "list": 2},
    {"vid": video_set_c[23], "img": negative_pictures[23], "valence": "negative", "n": 72 , "list": 2},
]

trial_list_mapping_3 = [
    {"vid": video_set_a[0], "img": positive_pictures[0], "valence": "positive", "n": 1 , "list": 3},
    {"vid": video_set_a[1], "img": positive_pictures[1], "valence": "positive", "n": 2 , "list": 3},
    {"vid": video_set_a[2], "img": positive_pictures[2], "valence": "positive", "n": 3 , "list": 3},
    {"vid": video_set_a[3], "img": positive_pictures[3], "valence": "positive", "n": 4 , "list": 3},
    {"vid": video_set_a[4], "img": positive_pictures[4], "valence": "positive", "n": 5 , "list": 3},
    {"vid": video_set_a[5], "img": positive_pictures[5], "valence": "positive", "n": 6 , "list": 3},
    {"vid": video_set_a[6], "img": positive_pictures[6], "valence": "positive", "n": 7 , "list": 3},
    {"vid": video_set_a[7], "img": positive_pictures[7], "valence": "positive", "n": 8 , "list": 3},
    {"vid": video_set_a[8], "img": positive_pictures[8], "valence": "positive", "n": 9 , "list": 3},
    {"vid": video_set_a[9], "img": positive_pictures[9], "valence": "positive", "n": 10 , "list": 3},
    {"vid": video_set_a[10], "img": positive_pictures[10], "valence": "positive", "n": 11 , "list": 3},
    {"vid": video_set_a[11], "img": positive_pictures[11], "valence": "positive", "n": 12 , "list": 3},
    {"vid": video_set_a[12], "img": positive_pictures[12], "valence": "positive", "n": 13 , "list": 3},
    {"vid": video_set_a[13], "img": positive_pictures[13], "valence": "positive", "n": 14 , "list": 3},
    {"vid": video_set_a[14], "img": positive_pictures[14], "valence": "positive", "n": 15 , "list": 3},
    {"vid": video_set_a[15], "img": positive_pictures[15], "valence": "positive", "n": 16 , "list": 3},
    {"vid": video_set_a[16], "img": positive_pictures[16], "valence": "positive", "n": 17 , "list": 3},
    {"vid": video_set_a[17], "img": positive_pictures[17], "valence": "positive", "n": 18 , "list": 3},
    {"vid": video_set_a[18], "img": positive_pictures[18], "valence": "positive", "n": 19 , "list": 3},
    {"vid": video_set_a[19], "img": positive_pictures[19], "valence": "positive", "n": 20 , "list": 3},
    {"vid": video_set_a[20], "img": positive_pictures[20], "valence": "positive", "n": 21 , "list": 3},
    {"vid": video_set_a[21], "img": positive_pictures[21], "valence": "positive", "n": 22 , "list": 3},
    {"vid": video_set_a[22], "img": positive_pictures[22], "valence": "positive", "n": 23 , "list": 3},
    {"vid": video_set_a[23], "img": positive_pictures[23], "valence": "positive", "n": 24 , "list": 3},
    {"vid": video_set_b[0], "img": negative_pictures[0], "valence": "negative", "n": 25 , "list": 3},
    {"vid": video_set_b[1], "img": negative_pictures[1], "valence": "negative", "n": 26 , "list": 3},
    {"vid": video_set_b[2], "img": negative_pictures[2], "valence": "negative", "n": 27 , "list": 3},
    {"vid": video_set_b[3], "img": negative_pictures[3], "valence": "negative", "n": 28 , "list": 3},
    {"vid": video_set_b[4], "img": negative_pictures[4], "valence": "negative", "n": 29 , "list": 3},
    {"vid": video_set_b[5], "img": negative_pictures[5], "valence": "negative", "n": 30 , "list": 3},
    {"vid": video_set_b[6], "img": negative_pictures[6], "valence": "negative", "n": 31 , "list": 3},
    {"vid": video_set_b[7], "img": negative_pictures[7], "valence": "negative", "n": 32 , "list": 3},
    {"vid": video_set_b[8], "img": negative_pictures[8], "valence": "negative", "n": 33 , "list": 3},
    {"vid": video_set_b[9], "img": negative_pictures[9], "valence": "negative", "n": 34 , "list": 3},
    {"vid": video_set_b[10], "img": negative_pictures[10], "valence": "negative", "n": 35 , "list": 3},
    {"vid": video_set_b[11], "img": negative_pictures[11], "valence": "negative", "n": 36 , "list": 3},
    {"vid": video_set_b[12], "img": negative_pictures[12], "valence": "negative", "n": 37 , "list": 3},
    {"vid": video_set_b[13], "img": negative_pictures[13], "valence": "negative", "n": 38 , "list": 3},
    {"vid": video_set_b[14], "img": negative_pictures[14], "valence": "negative", "n": 39 , "list": 3},
    {"vid": video_set_b[15], "img": negative_pictures[15], "valence": "negative", "n": 40 , "list": 3},
    {"vid": video_set_b[16], "img": negative_pictures[16], "valence": "negative", "n": 41 , "list": 3},
    {"vid": video_set_b[17], "img": negative_pictures[17], "valence": "negative", "n": 42 , "list": 3},
    {"vid": video_set_b[18], "img": negative_pictures[18], "valence": "negative", "n": 43 , "list": 3},
    {"vid": video_set_b[19], "img": negative_pictures[19], "valence": "negative", "n": 44 , "list": 3},
    {"vid": video_set_b[20], "img": negative_pictures[20], "valence": "negative", "n": 45 , "list": 3},
    {"vid": video_set_b[21], "img": negative_pictures[21], "valence": "negative", "n": 46 , "list": 3},
    {"vid": video_set_b[22], "img": negative_pictures[22], "valence": "negative", "n": 47 , "list": 3},
    {"vid": video_set_b[23], "img": negative_pictures[23], "valence": "negative", "n": 48 , "list": 3},
    {"vid": video_set_c[0], "img": neutral_pictures[0], "valence": "neutral", "n": 49 , "list": 3},
    {"vid": video_set_c[1], "img": neutral_pictures[1], "valence": "neutral", "n": 50 , "list": 3},
    {"vid": video_set_c[2], "img": neutral_pictures[2], "valence": "neutral", "n": 51 , "list": 3},
    {"vid": video_set_c[3], "img": neutral_pictures[3], "valence": "neutral", "n": 52 , "list": 3},
    {"vid": video_set_c[4], "img": neutral_pictures[4], "valence": "neutral", "n": 53 , "list": 3},
    {"vid": video_set_c[5], "img": neutral_pictures[5], "valence": "neutral", "n": 54 , "list": 3},
    {"vid": video_set_c[6], "img": neutral_pictures[6], "valence": "neutral", "n": 55 , "list": 3},
    {"vid": video_set_c[7], "img": neutral_pictures[7], "valence": "neutral", "n": 56 , "list": 3},
    {"vid": video_set_c[8], "img": neutral_pictures[8], "valence": "neutral", "n": 57 , "list": 3},
    {"vid": video_set_c[9], "img": neutral_pictures[9], "valence": "neutral", "n": 58 , "list": 3},
    {"vid": video_set_c[10], "img": neutral_pictures[10], "valence": "neutral", "n": 59 , "list": 3},
    {"vid": video_set_c[11], "img": neutral_pictures[11], "valence": "neutral", "n": 60 , "list": 3},
    {"vid": video_set_c[12], "img": neutral_pictures[12], "valence": "neutral", "n": 61 , "list": 3},
    {"vid": video_set_c[13], "img": neutral_pictures[13], "valence": "neutral", "n": 62 , "list": 3},
    {"vid": video_set_c[14], "img": neutral_pictures[14], "valence": "neutral", "n": 63 , "list": 3},
    {"vid": video_set_c[15], "img": neutral_pictures[15], "valence": "neutral", "n": 64 , "list": 3},
    {"vid": video_set_c[16], "img": neutral_pictures[16], "valence": "neutral", "n": 65 , "list": 3},
    {"vid": video_set_c[17], "img": neutral_pictures[17], "valence": "neutral", "n": 66 , "list": 3},
    {"vid": video_set_c[18], "img": neutral_pictures[18], "valence": "neutral", "n": 67 , "list": 3},
    {"vid": video_set_c[19], "img": neutral_pictures[19], "valence": "neutral", "n": 68 , "list": 3},
    {"vid": video_set_c[20], "img": neutral_pictures[20], "valence": "neutral", "n": 69 , "list": 3},
    {"vid": video_set_c[21], "img": neutral_pictures[21], "valence": "neutral", "n": 70 , "list": 3},
    {"vid": video_set_c[22], "img": neutral_pictures[22], "valence": "neutral", "n": 71 , "list": 3},
    {"vid": video_set_c[23], "img": neutral_pictures[23], "valence": "neutral", "n": 72 , "list": 3},
]

trial_list_mapping_3_block_1 = [
    {"vid": video_set_a[0], "img": positive_pictures[0], "valence": "positive", "n": 1 , "list": 3},
    {"vid": video_set_a[1], "img": positive_pictures[1], "valence": "positive", "n": 2 , "list": 3},
    {"vid": video_set_a[2], "img": positive_pictures[2], "valence": "positive", "n": 3 , "list": 3},
    {"vid": video_set_a[3], "img": positive_pictures[3], "valence": "positive", "n": 4 , "list": 3},
    {"vid": video_set_a[4], "img": positive_pictures[4], "valence": "positive", "n": 5 , "list": 3},
    {"vid": video_set_a[5], "img": positive_pictures[5], "valence": "positive", "n": 6 , "list": 3},
    {"vid": video_set_a[6], "img": positive_pictures[6], "valence": "positive", "n": 7 , "list": 3},
    {"vid": video_set_a[7], "img": positive_pictures[7], "valence": "positive", "n": 8 , "list": 3},

    {"vid": video_set_b[0], "img": negative_pictures[0], "valence": "negative", "n": 25 , "list": 3},
    {"vid": video_set_b[1], "img": negative_pictures[1], "valence": "negative", "n": 26 , "list": 3},
    {"vid": video_set_b[2], "img": negative_pictures[2], "valence": "negative", "n": 27 , "list": 3},
    {"vid": video_set_b[3], "img": negative_pictures[3], "valence": "negative", "n": 28 , "list": 3},
    {"vid": video_set_b[4], "img": negative_pictures[4], "valence": "negative", "n": 29 , "list": 3},
    {"vid": video_set_b[5], "img": negative_pictures[5], "valence": "negative", "n": 30 , "list": 3},
    {"vid": video_set_b[6], "img": negative_pictures[6], "valence": "negative", "n": 31 , "list": 3},
    {"vid": video_set_b[7], "img": negative_pictures[7], "valence": "negative", "n": 32 , "list": 3},

    {"vid": video_set_c[0], "img": neutral_pictures[0], "valence": "neutral", "n": 49 , "list": 3},
    {"vid": video_set_c[1], "img": neutral_pictures[1], "valence": "neutral", "n": 50 , "list": 3},
    {"vid": video_set_c[2], "img": neutral_pictures[2], "valence": "neutral", "n": 51 , "list": 3},
    {"vid": video_set_c[3], "img": neutral_pictures[3], "valence": "neutral", "n": 52 , "list": 3},
    {"vid": video_set_c[4], "img": neutral_pictures[4], "valence": "neutral", "n": 53 , "list": 3},
    {"vid": video_set_c[5], "img": neutral_pictures[5], "valence": "neutral", "n": 54 , "list": 3},
    {"vid": video_set_c[6], "img": neutral_pictures[6], "valence": "neutral", "n": 55 , "list": 3},
    {"vid": video_set_c[7], "img": neutral_pictures[7], "valence": "neutral", "n": 56 , "list": 3},
]

trial_list_mapping_3_block_2 = [
    {"vid": video_set_a[8], "img": positive_pictures[8], "valence": "positive", "n": 9 , "list": 3},
    {"vid": video_set_a[9], "img": positive_pictures[9], "valence": "positive", "n": 10 , "list": 3},
    {"vid": video_set_a[10], "img": positive_pictures[10], "valence": "positive", "n": 11 , "list": 3},
    {"vid": video_set_a[11], "img": positive_pictures[11], "valence": "positive", "n": 12 , "list": 3},
    {"vid": video_set_a[12], "img": positive_pictures[12], "valence": "positive", "n": 13 , "list": 3},
    {"vid": video_set_a[13], "img": positive_pictures[13], "valence": "positive", "n": 14 , "list": 3},
    {"vid": video_set_a[14], "img": positive_pictures[14], "valence": "positive", "n": 15 , "list": 3},
    {"vid": video_set_a[15], "img": positive_pictures[15], "valence": "positive", "n": 16 , "list": 3},

    {"vid": video_set_b[8], "img": negative_pictures[8], "valence": "negative", "n": 33 , "list": 3},
    {"vid": video_set_b[9], "img": negative_pictures[9], "valence": "negative", "n": 34 , "list": 3},
    {"vid": video_set_b[10], "img": negative_pictures[10], "valence": "negative", "n": 35 , "list": 3},
    {"vid": video_set_b[11], "img": negative_pictures[11], "valence": "negative", "n": 36 , "list": 3},
    {"vid": video_set_b[12], "img": negative_pictures[12], "valence": "negative", "n": 37 , "list": 3},
    {"vid": video_set_b[13], "img": negative_pictures[13], "valence": "negative", "n": 38 , "list": 3},
    {"vid": video_set_b[14], "img": negative_pictures[14], "valence": "negative", "n": 39 , "list": 3},
    {"vid": video_set_b[15], "img": negative_pictures[15], "valence": "negative", "n": 40 , "list": 3},

    {"vid": video_set_c[8], "img": neutral_pictures[8], "valence": "neutral", "n": 57 , "list": 3},
    {"vid": video_set_c[9], "img": neutral_pictures[9], "valence": "neutral", "n": 58 , "list": 3},
    {"vid": video_set_c[10], "img": neutral_pictures[10], "valence": "neutral", "n": 59 , "list": 3},
    {"vid": video_set_c[11], "img": neutral_pictures[11], "valence": "neutral", "n": 60 , "list": 3},
    {"vid": video_set_c[12], "img": neutral_pictures[12], "valence": "neutral", "n": 61 , "list": 3},
    {"vid": video_set_c[13], "img": neutral_pictures[13], "valence": "neutral", "n": 62 , "list": 3},
    {"vid": video_set_c[14], "img": neutral_pictures[14], "valence": "neutral", "n": 63 , "list": 3},
    {"vid": video_set_c[15], "img": neutral_pictures[15], "valence": "neutral", "n": 64 , "list": 3},
]

trial_list_mapping_3_block_3 = [
    {"vid": video_set_a[16], "img": positive_pictures[16], "valence": "positive", "n": 17 , "list": 3},
    {"vid": video_set_a[17], "img": positive_pictures[17], "valence": "positive", "n": 18 , "list": 3},
    {"vid": video_set_a[18], "img": positive_pictures[18], "valence": "positive", "n": 19 , "list": 3},
    {"vid": video_set_a[19], "img": positive_pictures[19], "valence": "positive", "n": 20 , "list": 3},
    {"vid": video_set_a[20], "img": positive_pictures[20], "valence": "positive", "n": 21 , "list": 3},
    {"vid": video_set_a[21], "img": positive_pictures[21], "valence": "positive", "n": 22 , "list": 3},
    {"vid": video_set_a[22], "img": positive_pictures[22], "valence": "positive", "n": 23 , "list": 3},
    {"vid": video_set_a[23], "img": positive_pictures[23], "valence": "positive", "n": 24 , "list": 3},

    {"vid": video_set_b[16], "img": negative_pictures[16], "valence": "negative", "n": 41 , "list": 3},
    {"vid": video_set_b[17], "img": negative_pictures[17], "valence": "negative", "n": 42 , "list": 3},
    {"vid": video_set_b[18], "img": negative_pictures[18], "valence": "negative", "n": 43 , "list": 3},
    {"vid": video_set_b[19], "img": negative_pictures[19], "valence": "negative", "n": 44 , "list": 3},
    {"vid": video_set_b[20], "img": negative_pictures[20], "valence": "negative", "n": 45 , "list": 3},
    {"vid": video_set_b[21], "img": negative_pictures[21], "valence": "negative", "n": 46 , "list": 3},
    {"vid": video_set_b[22], "img": negative_pictures[22], "valence": "negative", "n": 47 , "list": 3},
    {"vid": video_set_b[23], "img": negative_pictures[23], "valence": "negative", "n": 48 , "list": 3},

    {"vid": video_set_c[16], "img": neutral_pictures[16], "valence": "neutral", "n": 65 , "list": 3},
    {"vid": video_set_c[17], "img": neutral_pictures[17], "valence": "neutral", "n": 66 , "list": 3},
    {"vid": video_set_c[18], "img": neutral_pictures[18], "valence": "neutral", "n": 67 , "list": 3},
    {"vid": video_set_c[19], "img": neutral_pictures[19], "valence": "neutral", "n": 68 , "list": 3},
    {"vid": video_set_c[20], "img": neutral_pictures[20], "valence": "neutral", "n": 69 , "list": 3},
    {"vid": video_set_c[21], "img": neutral_pictures[21], "valence": "neutral", "n": 70 , "list": 3},
    {"vid": video_set_c[22], "img": neutral_pictures[22], "valence": "neutral", "n": 71 , "list": 3},
    {"vid": video_set_c[23], "img": neutral_pictures[23], "valence": "neutral", "n": 72 , "list": 3},

]

df = pd.DataFrame(trial_list_mapping_1_block_1)
df.to_csv("trial_list_mapping_1_block_1.csv", index=False)
df = pd.DataFrame(trial_list_mapping_1_block_2)
df.to_csv("trial_list_mapping_1_block_2.csv", index=False)
df = pd.DataFrame(trial_list_mapping_1_block_3)
df.to_csv("trial_list_mapping_1_block_3.csv", index=False)

df = pd.DataFrame(trial_list_mapping_2_block_1)
df.to_csv("trial_list_mapping_2_block_1.csv", index=False)
df = pd.DataFrame(trial_list_mapping_2_block_2)
df.to_csv("trial_list_mapping_2_block_2.csv", index=False)
df = pd.DataFrame(trial_list_mapping_2_block_3)
df.to_csv("trial_list_mapping_2_block_3.csv", index=False)

df = pd.DataFrame(trial_list_mapping_3_block_1)
df.to_csv("trial_list_mapping_3_block_1.csv", index=False)
df = pd.DataFrame(trial_list_mapping_3_block_2)
df.to_csv("trial_list_mapping_3_block_2.csv", index=False)
df = pd.DataFrame(trial_list_mapping_3_block_3)
df.to_csv("trial_list_mapping_3_block_3.csv", index=False)

